/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    stm32g4xx_hal_msp.c
  * @brief   HAL MSP (MCU Support Package) — peripheral clock and GPIO setup.
  *
  *          This file is manually maintained (not auto-generated by CubeMX).
  *          CubeMX USER CODE markers are present so that a future CubeMX
  *          regeneration preserves the custom content between the markers.
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "can_init_diag.h"
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

void HAL_MspInit(void)
{
  /* USER CODE BEGIN MspInit 0 */

  /* USER CODE END MspInit 0 */
  __HAL_RCC_SYSCFG_CLK_ENABLE();
  __HAL_RCC_PWR_CLK_ENABLE();
  /* USER CODE BEGIN MspInit 1 */

  /* USER CODE END MspInit 1 */
}

void HAL_FDCAN_MspInit(FDCAN_HandleTypeDef* hfdcan)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(hfdcan->Instance==FDCAN1)
  {
  /* USER CODE BEGIN FDCAN1_MspInit 0 */

  /* USER CODE END FDCAN1_MspInit 0 */

    /* ================================================================
     * STEP 1: Force FDCAN kernel clock source to PCLK1 BEFORE enabling
     * the peripheral clock.  After any reset FDCANSEL defaults to
     * 00 = HSE which is NOT enabled in this project (HSI + PLL).
     * Setting the source first avoids any window where the peripheral
     * gate is open with the wrong (or absent) kernel clock.
     * ================================================================ */
    __HAL_RCC_FDCAN_CONFIG(RCC_FDCANCLKSOURCE_PCLK1);
    __DSB();

    /* Readback-verify FDCANSEL.  On some G4 revisions the first write
     * after a system reset may not latch reliably.                     */
    if (__HAL_RCC_GET_FDCAN_SOURCE() != RCC_FDCANCLKSOURCE_PCLK1) {
        __HAL_RCC_FDCAN_CONFIG(RCC_FDCANCLKSOURCE_PCLK1);
        __DSB();
    }
    can_init_diag.msp_ccipr_ok =
        (__HAL_RCC_GET_FDCAN_SOURCE() == RCC_FDCANCLKSOURCE_PCLK1) ? 1U : 0U;

    /* ================================================================
     * STEP 2: Enable the FDCAN APB1 bus clock.
     * ================================================================ */
    __HAL_RCC_FDCAN_CLK_ENABLE();

    /* Readback-verify the clock-enable bit latched in APB1ENR1.
     * RCC_APB1ENR1_FDCANEN is bit 25 on STM32G4.                      */
    if (!(RCC->APB1ENR1 & RCC_APB1ENR1_FDCANEN)) {
        /* Critical: clock not enabled — peripheral reads will be garbage.
         * Record in diagnostics and continue (caller will detect via
         * CCCR validation).                                             */
        can_init_diag.msp_clk_ok = 0U;
    } else {
        can_init_diag.msp_clk_ok = 1U;
    }

    /* ================================================================
     * STEP 3: Robust peripheral reset sequence.
     * Force-reset clears all FDCAN registers to power-on defaults,
     * eliminating stale bus-off / CCCR.CSA flags from prior life.
     * ================================================================ */
    __HAL_RCC_FDCAN_FORCE_RESET();
    __DSB();
    __ISB();
    /* ≥4 AHB cycles for the reset assertion to propagate through the
     * bus bridge on all G4 silicon revisions.                          */
    __NOP(); __NOP(); __NOP(); __NOP();
    __HAL_RCC_FDCAN_RELEASE_RESET();
    __DSB();
    __ISB();

    /* After force-reset the clock gate may be in an indeterminate
     * state.  Re-enable APB1 clock and re-apply kernel clock source.  */
    __HAL_RCC_FDCAN_CLK_ENABLE();

    /* Re-apply FDCANSEL after reset — force-reset may clear CCIPR
     * bits on some G4 silicon revisions.                               */
    __HAL_RCC_FDCAN_CONFIG(RCC_FDCANCLKSOURCE_PCLK1);
    __DSB();

    /* Readback-verify FDCANSEL after reset sequence.  Re-apply once
     * more if the first post-reset write did not stick.                */
    if (__HAL_RCC_GET_FDCAN_SOURCE() != RCC_FDCANCLKSOURCE_PCLK1) {
        __HAL_RCC_FDCAN_CONFIG(RCC_FDCANCLKSOURCE_PCLK1);
        __DSB();
    }
    __ISB();

    /* Update diagnostics with final state after reset sequence.        */
    can_init_diag.msp_ccipr_ok =
        (__HAL_RCC_GET_FDCAN_SOURCE() == RCC_FDCANCLKSOURCE_PCLK1) ? 1U : 0U;
    can_init_diag.msp_clk_ok =
        (RCC->APB1ENR1 & RCC_APB1ENR1_FDCANEN) ? 1U : 0U;

    /* ================================================================
     * STEP 4: Adaptive poll — wait for the FDCAN peripheral to respond
     * with valid register data.  After force-reset the APB1 bus bridge
     * pipeline may return stale AHB data (flash addresses like
     * 0x08007d8d) until the clock gate fully propagates.
     *
     * Poll CCCR until reserved bits [31:16] read zero.  A 50 ms
     * SysTick-based timeout prevents an infinite loop on hardware
     * failure.  No fixed delays — exit as soon as peripheral responds.
     * ================================================================ */
#define FDCAN_CLK_READY_TIMEOUT_MS  50U
    {
        uint32_t msp_start = HAL_GetTick();
        uint8_t  cccr_ok   = 0U;
        can_init_diag.timeout_flag = 0U;
        while ((HAL_GetTick() - msp_start) < FDCAN_CLK_READY_TIMEOUT_MS) {
            uint32_t cccr = hfdcan->Instance->CCCR;
            if ((cccr & 0xFFFF0000U) == 0U) {
                cccr_ok = 1U;  /* Reserved bits zero — peripheral is live */
                break;
            }
        }
        if (!cccr_ok) {
            /* Timeout: peripheral did not respond within 50 ms.  Record
             * the flag; caller (MX_FDCAN1_Init) will detect via CCCR
             * triple-read validation and retry.                        */
            can_init_diag.timeout_flag = 1U;
        }
    }

    /* ================================================================
     * STEP 5: GPIO configuration for FDCAN1.
     * PA11 = FDCAN1_RX (CN10 pin 14)
     * PA12 = FDCAN1_TX (CN10 pin 12)
     * ================================================================ */
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitStruct.Pin = GPIO_PIN_11|GPIO_PIN_12;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF9_FDCAN1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    /* ================================================================
     * STEP 6: NVIC interrupt configuration.
     * ================================================================ */
    HAL_NVIC_SetPriority(FDCAN1_IT0_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(FDCAN1_IT0_IRQn);
    HAL_NVIC_SetPriority(FDCAN1_IT1_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(FDCAN1_IT1_IRQn);
  /* USER CODE BEGIN FDCAN1_MspInit 1 */

  /* USER CODE END FDCAN1_MspInit 1 */
  }
}

void HAL_TIM_Base_MspInit(TIM_HandleTypeDef* htim_base)
{
  if(htim_base->Instance==TIM1)
  {
  /* USER CODE BEGIN TIM1_MspInit 0 */

  /* USER CODE END TIM1_MspInit 0 */
    __HAL_RCC_TIM1_CLK_ENABLE();
    HAL_NVIC_SetPriority(TIM1_UP_TIM16_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM1_UP_TIM16_IRQn);
  /* USER CODE BEGIN TIM1_MspInit 1 */

  /* USER CODE END TIM1_MspInit 1 */
  }
  else if(htim_base->Instance==TIM2)
  {
  /* USER CODE BEGIN TIM2_MspInit 0 */

  /* USER CODE END TIM2_MspInit 0 */
    __HAL_RCC_TIM2_CLK_ENABLE();
    HAL_NVIC_SetPriority(TIM2_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM2_IRQn);
  /* USER CODE BEGIN TIM2_MspInit 1 */

  /* USER CODE END TIM2_MspInit 1 */
  }
  else if(htim_base->Instance==TIM3)
  {
  /* USER CODE BEGIN TIM3_MspInit 0 */

  /* USER CODE END TIM3_MspInit 0 */
    __HAL_RCC_TIM3_CLK_ENABLE();
    /* No interrupt for TIM3 — PWM output only (RPWM_STEER, LPWM_STEER) */
  /* USER CODE BEGIN TIM3_MspInit 1 */

  /* USER CODE END TIM3_MspInit 1 */
  }
  else if(htim_base->Instance==TIM8)
  {
  /* USER CODE BEGIN TIM8_MspInit 0 */

  /* USER CODE END TIM8_MspInit 0 */
    __HAL_RCC_TIM8_CLK_ENABLE();
    HAL_NVIC_SetPriority(TIM8_UP_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM8_UP_IRQn);
  /* USER CODE BEGIN TIM8_MspInit 1 */

  /* USER CODE END TIM8_MspInit 1 */
  }
}

void HAL_TIM_PWM_MspInit(TIM_HandleTypeDef* htim_pwm)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim_pwm->Instance==TIM1)
  {
  /* USER CODE BEGIN TIM1_PWM_MspInit 0 */

  /* USER CODE END TIM1_PWM_MspInit 0 */
    __HAL_RCC_TIM1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    
    /* PA8=RPWM_FL (TIM1_CH1), PA9=LPWM_FL (TIM1_CH2),
     * PA10=RPWM_FR (TIM1_CH3).
     * PA11 was TIM1_CH4 (LPWM_FR) but is now FDCAN1_RX;
     * LPWM_FR moved to TIM15_CH1 / PB14.                 */
    GPIO_InitStruct.Pin = GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF6_TIM1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  /* USER CODE BEGIN TIM1_PWM_MspInit 1 */

  /* USER CODE END TIM1_PWM_MspInit 1 */
  }
  else if(htim_pwm->Instance==TIM3)
  {
  /* USER CODE BEGIN TIM3_PWM_MspInit 0 */

  /* USER CODE END TIM3_PWM_MspInit 0 */
    __HAL_RCC_TIM3_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    /* PA6=RPWM_STEER (TIM3_CH1), PA7=LPWM_STEER (TIM3_CH2) */
    GPIO_InitStruct.Pin = GPIO_PIN_6|GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF2_TIM3;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  /* USER CODE BEGIN TIM3_PWM_MspInit 1 */

  /* USER CODE END TIM3_PWM_MspInit 1 */
  }
  else if(htim_pwm->Instance==TIM8)
  {
  /* USER CODE BEGIN TIM8_PWM_MspInit 0 */

  /* USER CODE END TIM8_PWM_MspInit 0 */
    __HAL_RCC_TIM8_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    
    /* PC6=RPWM_RL (TIM8_CH1), PC7=LPWM_RL (TIM8_CH2),
     * PC8=RPWM_RR (TIM8_CH3), PC9=LPWM_RR (TIM8_CH4) */
    GPIO_InitStruct.Pin = GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF4_TIM8;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
  /* USER CODE BEGIN TIM8_PWM_MspInit 1 */

  /* USER CODE END TIM8_PWM_MspInit 1 */
  }
  else if(htim_pwm->Instance==TIM15)
  {
    __HAL_RCC_TIM15_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* PB14 = LPWM_FR (TIM15_CH1, AF1) — front-right motor reverse PWM.
     * Moved here from PB9/TIM17_CH1 to avoid JP7 bootloader conflict. */
    GPIO_InitStruct.Pin = GPIO_PIN_14;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM15;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
  }
}

void HAL_I2C_MspInit(I2C_HandleTypeDef* hi2c)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(hi2c->Instance==I2C1)
  {
  /* USER CODE BEGIN I2C1_MspInit 0 */

  /* USER CODE END I2C1_MspInit 0 */
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_I2C1_CLK_ENABLE();
    
    GPIO_InitStruct.Pin = GPIO_PIN_6|GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_OD;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF4_I2C1;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    
    HAL_NVIC_SetPriority(I2C1_EV_IRQn, 3, 0);
    HAL_NVIC_EnableIRQ(I2C1_EV_IRQn);
    HAL_NVIC_SetPriority(I2C1_ER_IRQn, 3, 0);
    HAL_NVIC_EnableIRQ(I2C1_ER_IRQn);
  /* USER CODE BEGIN I2C1_MspInit 1 */

  /* USER CODE END I2C1_MspInit 1 */
  }
}

/* ADC MSP init — primary pedal channel on PA3 (ADC1_IN4)
 * Voltage divider (10 kΩ + 6.8 kΩ) scales 5V pedal to 0–3.3V range. */
void HAL_ADC_MspInit(ADC_HandleTypeDef* hadc)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(hadc->Instance==ADC1)
  {
  /* USER CODE BEGIN ADC1_MspInit 0 */

  /* USER CODE END ADC1_MspInit 0 */
    __HAL_RCC_ADC12_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitStruct.Pin = GPIO_PIN_3;     /* PA3 = ADC1_IN4 */
    GPIO_InitStruct.Mode = GPIO_MODE_ANALOG;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  /* USER CODE BEGIN ADC1_MspInit 1 */

  /* USER CODE END ADC1_MspInit 1 */
  }
}

void HAL_TIM_MspPostInit(TIM_HandleTypeDef* htim)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim->Instance==TIM1)
  {
    __HAL_RCC_GPIOA_CLK_ENABLE();
    
    GPIO_InitStruct.Pin = GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF6_TIM1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  }
  else if(htim->Instance==TIM3)
  {
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitStruct.Pin = GPIO_PIN_6|GPIO_PIN_7;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF2_TIM3;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
  }
  else if(htim->Instance==TIM8)
  {
    __HAL_RCC_GPIOC_CLK_ENABLE();
    
    GPIO_InitStruct.Pin = GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF4_TIM8;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
  }
  else if(htim->Instance==TIM15)
  {
    __HAL_RCC_GPIOB_CLK_ENABLE();

    GPIO_InitStruct.Pin = GPIO_PIN_14;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM15;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
  }
}

void HAL_TIM_Encoder_MspInit(TIM_HandleTypeDef* htim_encoder)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(htim_encoder->Instance==TIM2)
  {
  /* USER CODE BEGIN TIM2_Encoder_MspInit 0 */

  /* USER CODE END TIM2_Encoder_MspInit 0 */
    __HAL_RCC_TIM2_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    
    GPIO_InitStruct.Pin = GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM2;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    
    GPIO_InitStruct.Pin = GPIO_PIN_3;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    GPIO_InitStruct.Alternate = GPIO_AF1_TIM2;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);
    
    HAL_NVIC_SetPriority(TIM2_IRQn, 2, 0);
    HAL_NVIC_EnableIRQ(TIM2_IRQn);
  /* USER CODE BEGIN TIM2_Encoder_MspInit 1 */

  /* USER CODE END TIM2_Encoder_MspInit 1 */
  }
}

/* USER CODE BEGIN 1 */

/* USER CODE END 1 */
